### ISSUE TITLE
Implementation for linux users

### ISSUE THREAD

**Issue by ethanpyth** [Sabyasachi-Seal/Certificate-Generator-MLSA#1]
We can achieve that by making a python script that will read the email of participant in email.xlsm file and will send them the mail and not with a macro in excel

**Comment by Sabyasachi-Seal** [comment]
The issue stands in converting from DOCX to PDF, since that can only be done by one package in python that uses Windows

**Comment by notnotrachit** [comment]
We can use libreoffice for the same as well. I am trying to implement it.

**Comment by Sabyasachi-Seal** [comment]
@notnotrachit you can try it , do let me know if it does work

**Comment by notnotrachit** [comment]
Ya, Its working, I will clean the code and make a pull requet, but for now, I am also trying to automate the mail sending on Linux as well

**Comment by Sabyasachi-Seal** [comment]
sure sure ! Great work

**Comment by ethanpyth** [comment]
@notnotrachit don't you need any python library for doing that???

**Comment by notnotrachit** [comment]
> @notnotrachit don't you need any python library for doing that???

No, we can use Libreoffice's headless mode cli to convert from pdf to docx

**Comment by ethanpyth** [comment]
> > @notnotrachit don't you need any python library for doing that???
> 
> No, we can use Libreoffice's headless mode cli to convert from pdf to docx

How does this mode work?

**Comment by ethanpyth** [comment]
> > @notnotrachit don't you need any python library for doing that???
> 
> No, we can use Libreoffice's headless mode cli to convert from pdf to docx

How does this mode work?

**Comment by Sabyasachi-Seal** [comment]
Guys I have shited the code to work on linux. 
You can check the web-app branch. 

Do tell if you guys have any suggestions.
