### ISSUE TITLE
How to solve this issue faced while trying to automate the emails?

### ISSUE THREAD

**Issue by Trilasha** [Sabyasachi-Seal/Certificate-Generator-MLSA#2]
![image](https://github.com/Sabyasachi-Seal/Certificate-Generator-MLSA/assets/95575615/11697b11-0e5d-4abb-b29f-f1c655289176)

Despite having enabled all the macros, after clicking the run button, the above error pops up everytime.
Error message: Runtime error '429' ActiveX component can't create object.

I have also tried running a few commands on the command line to fix the issue, but nothing worked.

How to resolve this issue?

**Comment by Sabyasachi-Seal** [comment]
Hello @Trilasha , apologies for the late reply. 
Are you using a 32-bit os ?

**Comment by Trilasha** [comment]
No issues...
I'm using 64-bit os

**Comment by Sabyasachi-Seal** [comment]
> No issues...
> I'm using 64-bit os 

Try this fix. This worked for some people.
https://youtu.be/bvBgvew6UA0

**Comment by Trilasha** [comment]
It didn't work. The error persists

**Comment by Sabyasachi-Seal** [comment]
Using any antivirus?

**Comment by Trilasha** [comment]
I had one earlier- McAfee but recently uninstalled it. Currently I'm having only the windows bydefault one.

**Comment by Sabyasachi-Seal** [comment]
@Trilasha I have now started shifting the entire application to a website. You should be able to use that to send mails.
