### ISSUE TITLE
Blank Mail.xlsm while downloading certificates

### ISSUE THREAD

**Issue by Akash-1627** [Sabyasachi-Seal/Certificate-Generator-MLSA#5]
The downoaded zip file contains a blank mail.xlsm file. Also the DOc and PDF folders are still empty.
Also, there was a code error due to which every time I clicked on Generate Certificate, it showed an alert stating "The CSV file must have 'Name' and 'Email' fields", even though the file already have 'Name' and 'Email' fields.

![Screenshot 2023-12-27 074318](https://github.com/Sabyasachi-Seal/Certificate-Generator-MLSA/assets/101383763/0aca6de4-71f3-4ab1-baa7-037e2ae166bf)

![Screenshot 2023-12-27 075113](https://github.com/Sabyasachi-Seal/Certificate-Generator-MLSA/assets/101383763/e2a2746c-d587-47e6-a5dc-03704ce0fbe0)

**Comment by Sabyasachi-Seal** [comment]
Hey Akash, thanks for reaching out.

Can you send me the csv file once ?

I checked application logs but nothing has appeared.

**Comment by Akash-1627** [comment]
Here is the CSV FIle.

[ParticipantList.csv](https://github.com/Sabyasachi-Seal/Certificate-Generator-MLSA/files/13775125/ParticipantList.csv)

**Comment by Sabyasachi-Seal** [comment]
Got it, I have found the issue. I will notify you when I have fixed it

**Comment by Akash-1627** [comment]
Sure. Thanks

**Comment by Sabyasachi-Seal** [comment]
@Akash-1627 This issue has been fixed. 
Thank you so much for reporting this bug :)

Please check if your able to generate. If yes, please do close this issue.
