### ISSUE TITLE
Prefer use a virtual environment instead installing all the requirements in local

### ISSUE THREAD

**Issue by ethanpyth** [Sabyasachi-Seal/Certificate-Generator-MLSA#6]
Using a virtual environment is a good practice in Python programming. I encourage you to update your readme.md file before the installation command of all requirements, write the command to create a virtual environment, also the venv activation command before installing any tools or library, and add it to the .gitignore file if it exists.

- here is a link showing the advantage to use that : 
[A guide to python virtual environment](https://builtin.com/data-science/python-virtual-environment#:~:text=Python%20Virtual%20Environments%3F-,Python%20virtual%20environments%20allow%20developers%20to%20control%20software%20dependencies%20in,from%20running%20code%20are%20reproducible.)

**Comment by Sabyasachi-Seal** [comment]
@ethanpyth I agree, 

Could you add the required changes and then add them asd a pr to this repo ?

**Comment by ethanpyth** [comment]
No problem, I can do that so assign it to me I will work on it...

**Comment by Sabyasachi-Seal** [comment]
@ethanpyth Assigned

**Comment by Sabyasachi-Seal** [comment]
@ethanpyth if your working on it , please submit a pr when ur confortable

**Comment by ethanpyth** [comment]
@Sabyasachi-Seal i did a pull request, you can take a look on it...

**Comment by Sabyasachi-Seal** [comment]
Sure, ill take a look at it
