### ISSUE TITLE
Linux

### ISSUE THREAD

**Issue by MTalhaofc** [Sabyasachi-Seal/Certificate-Generator-MLSA#7]
When you're gonna release it for linux?

**Comment by Sabyasachi-Seal** [comment]
https://mlsa-certificate-generator.iamseal.tech/

**Comment by MTalhaofc** [comment]
I only want to get certificates, by using this I could got that. It shows the main system

**Comment by Sabyasachi-Seal** [comment]
This site would get you the certicates, you just need to upload the file and put the event name and the certificate name
