### ISSUE TITLE
Send Emails directly from Dashboard

### ISSUE THREAD

**Issue by Ramseyxlil** [Sabyasachi-Seal/Certificate-Generator-MLSA#8]
I noticed that after generating the certificates, users still have to manually send them via email from Excel. I think it would be more convenient if users could grant access to their MLSA email directly from the dashboard, allowing them to send the certificates with just one click. It's like hitting the send button, but even easier.

**Comment by Sabyasachi-Seal** [comment]
Sounds good, lets start working on this

**Comment by Ramseyxlil** [comment]
I will go through the code base i can easily work on the backend but the frontend i am not good at that

**Comment by Sabyasachi-Seal** [comment]
No worries, i can take care of the frontend, we need to figure out and make the backend first

**Comment by Ramseyxlil** [comment]
okay  i will check that

**Comment by Sabyasachi-Seal** [comment]
Hey guys, I have implemented this, please check web-app-2 branch
